name: Site Change Monitor

on:
  schedule:
    # הרצה כל שעה
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer node-fetch
    
    - name: Run monitor script
      env:
        SITE_USERNAME: ${{ secrets.SITE_USERNAME }}
        SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: node monitor.js
