name: Site Change Monitor

on:
  schedule:
    # הרצה כל 5 MINUTSה
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer node-fetch
    
    - name: Run monitor script
      env:
        SITE_txtTZparents: ${{ secrets.SITE_txtTZparents }}
        SITE_BIRTHDAY: ${{ secrets.SITE_BIRTHDAY }}
        SITE_txtTZkid: ${{ secrets.SITE_txtTZkid }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: node monitor.js
